basePath: /v2
definitions:
  dto.ErrorDTO:
    properties:
      message:
        type: string
      statusCode:
        type: integer
    type: object
  dto.QuotationInputDTO:
    properties:
      ask:
        type: string
      bid:
        type: string
      code:
        type: string
      codein:
        type: string
      high:
        type: string
      id:
        type: string
      low:
        type: string
      name:
        type: string
      pctChange:
        type: string
      timestamp:
        type: string
      varBid:
        type: string
    type: object
  dto.QuotationOutputDTO:
    properties:
      ask:
        type: string
      bid:
        type: string
      createdAt:
        type: string
      deletedAt:
        type: string
      id:
        type: string
      updatedAt:
        type: string
    type: object
host: localhost:8081
info:
  contact:
    email: diegocordeiro.contatos@gmail.com
    name: Diego Cordeiro
    url: https://github.com/DiegoJCordeiro/client-server-activity-go
  description: API to query USD current value
  license:
    name: Diego Cordeiro License
    url: https://github.com/DiegoJCordeiro/client-server-activity-go/blob/main/LICENSE
  termsOfService: http://swagger.io/terms/
  title: Server - GO Expert - Activity
  version: "1.0"
paths:
  /quotation:
    delete:
      consumes:
      - application/json
      description: This endpoint is used to Delete a quotation.
      parameters:
      - description: Quotation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.QuotationInputDTO'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.QuotationOutputDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorDTO'
      summary: Delete a quotation
      tags:
      - Quotation
    get:
      consumes:
      - application/json
      description: This endpoint is used to Query a quotation.
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.QuotationOutputDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorDTO'
      summary: Query a quotation
      tags:
      - Quotation
    post:
      consumes:
      - application/json
      description: This endpoint is used to Query a quotation.
      parameters:
      - description: Quotation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.QuotationInputDTO'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/dto.QuotationOutputDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorDTO'
      summary: Create a quotation
      tags:
      - Quotation
    put:
      consumes:
      - application/json
      description: This endpoint is used to Update a quotation.
      parameters:
      - description: Quotation Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/dto.QuotationInputDTO'
      responses:
        "204":
          description: No Content
          schema:
            $ref: '#/definitions/dto.QuotationOutputDTO'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/dto.ErrorDTO'
      summary: Update a quotation
      tags:
      - Quotation
swagger: "2.0"
