// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type Quotation struct {
	ID        string
	Bid       sql.NullString
	Ask       sql.NullString
	Timestamp sql.NullString
	CreatedAt sql.NullTime
	DeletedAt sql.NullTime
	UpdatedAt sql.NullTime
}
