// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "Diego Cordeiro",
            "url": "https://github.com/DiegoJCordeiro/client-server-activity-go",
            "email": "diegocordeiro.contatos@gmail.com"
        },
        "license": {
            "name": "Diego Cordeiro License",
            "url": "https://github.com/DiegoJCordeiro/client-server-activity-go/blob/main/LICENSE"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/quotation": {
            "get": {
                "description": "This endpoint is used to Query a quotation.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Quotation"
                ],
                "summary": "Query a quotation",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.QuotationOutputUseCaseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorDTO"
                        }
                    }
                }
            },
            "put": {
                "description": "This endpoint is used to Update a quotation.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Quotation"
                ],
                "summary": "Update a quotation",
                "parameters": [
                    {
                        "description": "Quotation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.QuotationInputHandlerUpdateDTO"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content",
                        "schema": {
                            "$ref": "#/definitions/dto.QuotationOutputUseCaseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorDTO"
                        }
                    }
                }
            },
            "post": {
                "description": "This endpoint is used to Query a quotation.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Quotation"
                ],
                "summary": "Create a quotation",
                "parameters": [
                    {
                        "description": "Quotation Request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.QuotationInputHandlerCreateDTO"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.QuotationOutputUseCaseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorDTO"
                        }
                    }
                }
            },
            "delete": {
                "description": "This endpoint is used to Delete a quotation.",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "Quotation"
                ],
                "summary": "Delete a quotation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "id quotation",
                        "name": "id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.QuotationOutputUseCaseDTO"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorDTO"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.ErrorDTO": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "dto.QuotationInputHandlerCreateDTO": {
            "type": "object",
            "properties": {
                "ask": {
                    "type": "string"
                },
                "bid": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.QuotationInputHandlerUpdateDTO": {
            "type": "object",
            "properties": {
                "ask": {
                    "type": "string"
                },
                "bid": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.QuotationOutputUseCaseDTO": {
            "type": "object",
            "properties": {
                "ask": {
                    "type": "string"
                },
                "bid": {
                    "type": "string"
                },
                "createdAt": {
                    "type": "string"
                },
                "deletedAt": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8081",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Server - GO Expert - Activity",
	Description:      "API to query USD current value",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
