CREATE TABLE IF NOT EXISTS Quotations (
  id TEXT PRIMARY KEY,
  bid TEXT,
  ask TEXT,
  timestamp TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
)